### ISSUE TITLE
Cannot call TT.fromfile() as a static method.

### ISSUE THREAD

**Issue by scrapcode** [Zulko/easyAI#27]
>>> from easyAI import TT
>>> table = TT.fromfile('testing.dat')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: fromfile() missing 1 required positional argument: 'filename'
>>> exit()

**Comment by JohnAD** [comment]
I've recreated the problem. The problem appears that the method is static, yet it oddly references self. I'm suspecting this function has never worked.

I'll fix this. It might take a few days or so as I'd like to add it to the test suite and documentation. I'll then update it to the repo and publish to pypi.

BTW, big caveat: because this method is essentially calling the pickling routine, the file created is specific to the version of python you are running as well as the version of easyAI. It is not universal.

(Would making this more universal be useful?...  It should be possible to save the TT as a JSON document, but it might not be a trivial feature to write.)

Thanks for catching the bug!

**Comment by scrapcode** [comment]
I noticed this bug when trying to help a user on IRC. I assumed that it
never worked to begin with as well. I cloned it and started writing a test
to fix the issue, but I just don't understand the context of your library
enough to know where to store the pickling.

**Comment by JohnAD** [comment]
@scrapcode I've fixed the bug and merged the fix. I've also published it to PyPI as version 1.0.0.4. The documentation has been updated and I've added a test to the unittest script.

Sorry about the delay in getting all this done.

Mind trying the library again?

BTW, I also added `to_json_file` and `from_json_file` methods to `TT()`, so that a safer (and universal) JSON files could be used instead of pickle. See reference docs for details.
